- hosts: master
  gather_facts: true
  tasks:
    - name: reset kubeadm
      become: true
      shell: kubeadm reset -f

    - name: get join command
      become: true
      shell: kubeadm token create --print-join-command
      register: join_command_raw
    - name: "add join cmd to dummy host"
      add_host:
        name: "K8S_JOIN_CMD"
        cmd: "{{ join_command_raw }}"


- hosts: workers
  tasks:
    - name:
      debug:
        msg: "[Worker] Join Command is {{ hostvars['K8S_JOIN_CMD']['cmd']['stdout'] }}"
    - name: join cluster
      become: true
      shell: "{{ hostvars['K8S_JOIN_CMD']['cmd']['stdout'] }}"
      args:
        creates: node_joined.txt
